---
title: "401_proj"
output: html_document
date: "2023-11-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
np = read.table("Downloads/np.csv", header=T, na.strings=".") %>%
arrange(SubscriptionId, t) %>%
group_by(SubscriptionId) %>%
mutate(nextchurn = lead(churn),
nextprice=lead(currprice),
t = t)
```

```{r}
np= np[,-c(16:28)]
np[which(np$t == 1),]$trial
cor(na.omit(np)$currprice,na.omit(np)$mobile)
```

```{r}
cor(np$regularity,np$intensity)
cor(na.omit(np)$trial,na.omit(np)$nextprice)
```

```{r}
np1 = np[np$SubscriptionId != np[np$t == 1 & np$trial == 1, ]$SubscriptionId,]
model1 = glm(nextchurn ~ t + nextprice + regularity + intensity, np1, family = binomial)
summary(model1)
```

```{r}
np2 = np[np$SubscriptionId != np[which(np$trial == 0),]$SubscriptionId,]
model1_2 = glm(nextchurn ~ t + trial + nextprice + regularity + intensity, np1, family = binomial)
summary(model1_2)
```


```{r}

# Fit a full model
full_model <- glm(nextchurn ~ t + trial + nextprice + sports1 + news1+ crime1 + life1 + obits1 + business1 +opinion1 + mobile +tablet + desktop + regularity, np, family = binomial)

# Perform stepwise model selection using AIC
stepwise_model <- step(full_model, direction = "both", trace = 0)

# Display the summary of the selected model
summary(stepwise_model)

```


```{r}
summary(glm(nextchurn ~ ., np, family = binomial))
```